# Generated by Django 5.2.4 on 2025-07-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('stage', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['stage'],
            },
        ),
    ]
